// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, ajax,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Promise = require("bluebird");

  ajax = function(action, json) {
    return new Promise(function(resolve, reject) {
      var complete, err, error1, req;
      req = new XMLHttpRequest();
      complete = function() {
        var ref, result, successResultCodes;
        if (req.readyState === 4) {
          successResultCodes = [200, 304];
          result = JSON.parse(req.responseText);
          if (ref = req.status, indexOf.call(successResultCodes, ref) >= 0) {
            return resolve(result);
          } else {
            result.status = req.status;
            return reject(result);
          }
        }
      };
      req.addEventListener("readystatechange", complete, false);
      try {
        req.open("POST", action);
        req.setRequestHeader("Content-Type", "application/json");
        return req.send(JSON.stringify(json));
      } catch (error1) {
        err = error1;
        return reject(JSON.parse(err));
      }
    });
  };

  module.exports = function(endpoint, actions, ticket, onlyif) {
    if (onlyif == null) {
      onlyif = function() {
        return true;
      };
    }
    return function(dispatch, getState) {
      var error, error1;
      if (onlyif(getState)) {
        dispatch({
          type: actions.request,
          ticket: ticket
        });
        try {
          return ajax(endpoint, ticket).then(function(response) {
            return dispatch({
              response: response,
              type: actions.complete,
              time: new Date()
            });
          })["catch"](function(error) {
            return dispatch({
              type: actions.error,
              message: error
            });
          });
        } catch (error1) {
          error = error1;
          return dispatch({
            type: actions.error,
            error: error.message
          });
        }
      }
    };
  };

}).call(this);
